name: Run AQI Pipeline

on:
  schedule:
    - cron: '0 0 * * *'    # 12:00 AM UTC = 5:30 AM IST  (Early Morning)
    - cron: '0 4 * * *'    # 4:00 AM UTC  = 9:30 AM IST  (Morning)
    - cron: '0 8 * * *'    # 8:00 AM UTC  = 1:30 PM IST  (Afternoon)
    - cron: '0 12 * * *'   # 12:00 PM UTC = 5:30 PM IST  (Evening)
    - cron: '0 16 * * *'   # 4:00 PM UTC  = 9:30 PM IST  (Night)
    - cron: '0 20 * * *'   # 8:00 PM UTC  = 1:30 AM IST  (Late Night)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write credentials file
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run pipeline
        run: python pipeline.py
        
